### ISSUE TITLE
Install of service not working

### ISSUE THREAD

**Issue by schneik80** [vineetred/flowy#39] opened 2020-07-17 06:12 UTC
**Describe the bug**  

I have installed on ubuntu and configured using the command line.

Running from cli works as expected:

```
schneik@xps13-9300:$ flowy --dir /home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/
Generated config file
Times - [
    "00:00",
    "01:00",
    "02:00",
    "03:00",
    "04:00",
    "05:00",
    "06:00",
    "07:00",
    "08:00",
    "09:00",
    "10:00",
    "11:00",
    "12:00",
    "13:00",
    "14:00",
    "15:00",
    "16:00",
    "17:00",
    "18:00",
    "19:00",
    "20:00",
    "21:00",
    "22:00",
    "23:00",
]
Paths - [
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-01.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-02.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-03.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-04.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-05.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-06.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-07.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-08.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-09.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-10.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-11.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-12.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-13.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-14.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-15.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-16.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-17.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-18.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-19.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-20.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-21.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-22.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-23.jpg",
    "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-24.jpg",
]
```

when trying to run as a service it fails:

```
schneik@xps13-9300:$ systemctl --user start flowy.service
schneik@xps13-9300:$ systemctl status flowy
● flowy.service
     Loaded: not-found (Reason: Unit flowy.service not found.)
     Active: failed (Result: exit-code) since Thu 2020-07-16 22:46:23 PDT; 9min ago
   Main PID: 38829 (code=exited, status=101)
```

**Steps to Reproduce**  
1.  Download flowy_0.2.5_amd64.deb
2.  Install (note no prompt to locate directory as README.MD claims)
3.  In CLI run  ```systemctl --user start flowy.service```
4.  No result. Flowy is not running.

**Other information**  
flowy.service file has placeholder txt ```--dir=REPLACEME```.  I assume this is the value that install shuld have promptem for and then used when creating flow.service.

I atempted to edit/replace this with ```--dir /path to images/``` and then ```--dir=/path to images/```. this did not work

I copied flowy.service from /etc/systemd/user to /etc/stystemd/system. this did not work

i ensured 

i can run flow from command line as expected but can not run as a service.

**Comment by vineetred** [comment] 2020-07-17 07:16
This is an interesting bug -- the deb installation seems to have added flowy to path but not included the service file. I've rebuilt the file and it is working on my local. Check it out -- I've added it again to the release. 

Also, the fact that you are able to see the service file in the directory ```/etc/systemd/user``` means that the installation worked. Not sure why ```systemd``` is unable to find the service file. 

Maybe this link could help - https://stackoverflow.com/questions/34501611/systemd-apparently-not-finding-service-file

**Comment by vineetred** [comment] 2020-07-17 18:01
I presume that flowy ended up working for you. I will close this issue in the next 12 hours. 

Post here if I am mistaken.

**Comment by schneik80** [comment] 2020-07-18 01:56
nope. i have tried the new deb and was able to get the prompt to locate the directory.
i still error out when trying to start the service:
```
Jul 17 18:53:35 xps13-9300 flowy[6727]:     "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-20.jpg",
Jul 17 18:53:35 xps13-9300 flowy[6727]:     "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-21.jpg",
Jul 17 18:53:35 xps13-9300 flowy[6727]:     "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-22.jpg",
Jul 17 18:53:35 xps13-9300 flowy[6727]:     "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-23.jpg",
Jul 17 18:53:35 xps13-9300 flowy[6727]:     "file:///home/schneik/Dropbox/Profile/backgrounds/Dessert/namibia/Namibia-24.jpg",
Jul 17 18:53:35 xps13-9300 flowy[6727]: ]
Jul 17 18:53:35 xps13-9300 flowy[6727]: thread 'main' panicked at 'Desktop envt could not be determined: NotPresent', flowy/src/lib.rs:161:24
Jul 17 18:53:35 xps13-9300 flowy[6727]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jul 17 18:53:35 xps13-9300 systemd[1]: flowy.service: Main process exited, code=exited, status=101/n/a
Jul 17 18:53:35 xps13-9300 systemd[1]: flowy.service: Failed with result 'exit-code'.
```

this is true with flowy.service in /etc/systemd/user/ or /etc/systemd/system

**Comment by vineetred** [comment] 2020-07-18 05:25
The systemd service file is very bare and all its doing is running the same CLI command you ran in the first comment. The error that flowy is throwing seems to say that it wasn't able to find the desktop environment, which is weird because it runs find if run through the command line. Your problem seems to lie in the way the systemd service permissions are set. I have a Ubuntu local and it works fine on it. 

I suggest you try fixing your systemd service as flowy seems to be working exactly as it is supposed to.  

Also, flowy.service must always be in the ```systemd/user``` directory

**Comment by zephyr697** [comment] 2020-07-18 20:44
@schneik80 Did you manage it to work? I'm getting the same error.

**Comment by schneik80** [comment] 2020-07-18 22:31
no,

**Comment by vineetred** [comment] 2020-07-19 05:22
Can you both set the backtrace to 1 and and run flowy? It'll generate a large data dump on the terminal. Post this here.

**Comment by zephyr697** [comment] 2020-07-19 07:46
@vineetred I'm sorry but I'm a linux noob and have no idea how to do that. Can you please elaborate?

**Comment by vineetred** [comment] 2020-07-19 11:15
Just run the command ```export RUST_BACKTRACE=1``` on your terminal. After this, run the flowy service and post all the logs here.

**Comment by Baldomo** [comment] 2020-07-22 10:46
@vineetred why was this issue closed? it has not been fixed upstream (and I can easily reproduce it on my machine):

```
Jul 22 12:37:19 laptop flowy[61597]: Paths - [
Jul 22 12:37:19 laptop flowy[61597]:     "file:///home/leo/Pictures/Wallpapers/Ghibli_Dynamic/DAY-01.jpeg",
Jul 22 12:37:19 laptop flowy[61597]:     "file:///home/leo/Pictures/Wallpapers/Ghibli_Dynamic/DAY-02.jpeg",
Jul 22 12:37:19 laptop flowy[61597]:     "file:///home/leo/Pictures/Wallpapers/Ghibli_Dynamic/DAY-03.jpeg",
Jul 22 12:37:19 laptop flowy[61597]:     "file:///home/leo/Pictures/Wallpapers/Ghibli_Dynamic/NIGHT-01.jpeg",
Jul 22 12:37:19 laptop flowy[61597]: ]
Jul 22 12:37:19 laptop flowy[61597]: thread 'main' panicked at 'Desktop envt could not be determined: NotPresent', flowy/src/lib.rs:164:24
Jul 22 12:37:19 laptop flowy[61597]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jul 22 12:37:19 laptop systemd[4281]: flowy.service: Main process exited, code=exited, status=101/n/a
Jul 22 12:37:19 laptop systemd[4281]: flowy.service: Failed with result 'exit-code'.
```

It is well known that **systemd unsets pretty much all environment variables** (it's a security feature) and there are several ways of providing environment variables to services ([see here](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines)), for example:
- [CoreOS docs](https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html)
- [Flatcar Linux docs](https://docs.flatcar-linux.org/os/using-environment-variables-in-systemd-units/)
- [Stackoverflow (2018)](https://stackoverflow.com/questions/52571577/issues-in-accessing-docker-environment-variables-in-systemd-service-files)
- [Serverfault (2012)](https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service)

**Comment by vineetred** [comment] 2020-07-22 10:51
Highly interesting! It seemed to be working fine on my end so I assumed the issue was related to a unsupported DE. Also, this was never an issue before? I am confused as to how it popped up this late. 

How should one go about fixing this?

**Comment by Baldomo** [comment] 2020-07-22 10:57
I suppose you can also ask for the desktop environment during the service installation procedure, as using this
```
[Unit]
Description=Flowy

[Service]
Environment=XDG_CURRENT_DESKTOP=<value>
ExecStart=<command>

[Install]
WantedBy=multi-user.target
```
works just fine (for example, I use XFCE so I'd set `<value>` to `XFCE`)

Edit: I also snooped around in the code for `directories-next` as it also uses `XDG_*` environment variables but the crate is able to work without them so the only one needed is `XDG_CURRENT_DESKTOP`

**Comment by vineetred** [comment] 2020-07-22 10:58
Hmmm this sort of makes the process rather tedious. I was planning on discontinuing the debian release and just support binaries instead. What do you think?

**Comment by Baldomo** [comment] 2020-07-22 12:27
Technically I think showing users how to setup the systemd service (maybe as a section in the readme or wiki) by themselves should be ok (the snippet I included in the comment above is pretty much all you need to have it working). In the end it's a single command so a quick web search will show how to auto-run it on startup for any system.

**Comment by schneik80** [comment] 2020-07-22 23:40
adding `Environment=XDG_CURRENT_DESKTOP=<value> ` was all i needed to fix the issue. i now have the service enabled and running as expected.

I simply used `echo $XDG_CURRENT_DESKTOP` to get the value I needed to add to the .service file 
If the install is asking for the image directory could the script gather this value and write it at install time?

**Comment by vineetred** [comment] 2020-07-23 04:31
@schneik80 that's great to hear. However, regarding your second point, I am planning to discontinue releasing the debian specific installation file. Instead, I plan on just posting the instructions on the README that shows how to setup flowy as a systemd service.

**Comment by schneik80** [comment] 2020-07-23 04:35
understood. the read me could also do with some examples of appropriate Lat and Log formats. I can log a separate issue if need be.

**Comment by vineetred** [comment] 2020-07-23 04:36
Yeah, the readme needs a big revamp anyways. Been caught up with work -- will get around to it this weekend hopefully.

**Comment by vineetred** [comment] 2020-07-24 13:32
I've fixed the README as well. I will keep this issue up for another week before taking it down as it may help others who are still relying on the Debian release.

**Closed as completed** 2020-07-29 13:05 UTC
Labels: bug
